# include <stdio.h>

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 
//  and 
// , the first 
//  terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

int main() {
    int a = 1, b = 2, sum = 0;
    while (b <= 4000000) {
        if (b % 2 == 0) {
            sum += b;
        }
        int next = a + b;
        a = b;
        b = next;
    }
    printf("%d\n", sum);
    return 0;
}